### ISSUE TITLE
[DemianFigueiredo](SQL_Project_2)

### ISSUE THREAD

**Issue by DemianFigueiredo** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#10]
https://github.com/DemianFigueiredo/sql-data-base-building.git

**Comment by OrianAmpuero** [comment]
Bien Demian!
-Buen readme y organización del repo
-Yo usaría el .gitignore para ocultar los archivos csv que tienes sucios y solo dejar a la vista los limpios
-Muy bien  las queries para mostrar los datos y sus relaciones
-Cuidado con estos 5 archivos (querie_1_result.xml, querie_2_result.xml.....) que no se entiendes, es preferible una captura de pantalla con el resultado
-No entiendo la carpeta scc con archivos .py

**Comment by DemianFigueiredo** [comment]
Gracias. Voy hacer los cambios futuramente. ;-)

**Comment by DemianFigueiredo** [comment]
perdoname, el nombre de la carpeta scc, esta roto. Corecto es src. perdon
