### ISSUE TITLE
[Carlos González](w3-project_SQL)

### ISSUE THREAD

**Issue by chiinwy** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#11]
https://github.com/chiinwy/Proyecto_SQL

**Comment by OrianAmpuero** [comment]
Bien Carlos, te pongo el feedback del que hablamos antes:
-Se puede mejorar el Readme
-Bien la organización de las carpetas del repo pero pendiente que te quedo un archivo por fuera
-Bien el jupyter notebook de limpieza pero recuerda poner head() para recortar el output
-En la carpeta data que tienes todos los archivos csv, yo usaría el .gitignore para ocultar los 'sucios' y solo dejar a la vista los que quedaron limpios para que se vea mejor
-Faltó captura de ERD
