### ISSUE TITLE
[Nico.V](BlockBuster_proyect)

### ISSUE THREAD

**Issue by nicovilla23** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#12]

**Comment by nicovilla23** [comment]
https://github.com/nicovilla23/Proyect_BlockBuster_DataBase

**Comment by OrianAmpuero** [comment]
Bien Nico,
-Buen readme y repo
-Yo solo dejaría la data limpia y los otros csv los pondría en .gitignore para que no se vean
-En cuanto a la limpieza bien y las queries de creación y llenado de info
-Bien el ERD pero no se porque dejaste Staff sin relacionar
