### ISSUE TITLE
[Rodrigo G] (w3-project_SQL)

### ISSUE THREAD

**Issue by rodrigogtz99** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#13]
https://github.com/rodrigogtz99/w3-project_SQL.git

**Comment by OrianAmpuero** [comment]
Bien Rodrigo, aquí va el feedback:
-Falta organización del repo, es difícil ubicar los archivos para ver el proyecto
-El readme es el de Ironhack
-En la carpeta data trata de dejar solo los csv limpios a la vista y los sucios se pueden guardar en .gitignore para que no se vean todos que puede confundir un poco
