### ISSUE TITLE
MartaMoral w3-proyect_SQL videoclub

### ISSUE THREAD

**Issue by MARTAMM77** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#14]
https://github.com/MARTAMM77/w3-project_SQLvideoclub.git

**Comment by MARTAMM77** [comment]
un poco lioso

**Comment by OrianAmpuero** [comment]
Marta te envío el feedback del proyecto:
-Pendiente que tienes un repo dentro de otro
-Recuerda organizar el repo en carpetas para tener todos los archivos organizados
-Ya mejoramos teniendo readme pero toca ir puliendo detalles para que se vea mejor (yo hubiese puesto el ERD de Workbech y por otra parte, es preferible no poner lo de ver las tablas en excel ya que lo ideal es en python como la herramienta que estamos aprendiendo a usar
-No pondría un archivo word ya que para eso esta el readme y también tienes el jupyter notebook para comentar tu código
-Falta captura del ERD para ver las tablas y sus relaciones
