### ISSUE TITLE
[NICO-GCD]-w3-project_SQL

### ISSUE THREAD

**Issue by NGCOS46** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#2]
https://github.com/NGCOS46/w3-project_SQL

**Comment by OrianAmpuero** [comment]
Bien Nico, aquí está el feedback del proyecto:

-Readme de Ironhack?
-Organizar los archivos en sus carpetas
-Yo usaría un solo jupyter para limpiar los csv ya que es muy puntual lo que se hace, además de dejar los csv sucios en el .gitignore para no tener todo a la vista en el repo
-Pendiente de no dejar errores printeados en el notebook, por ejemplo el de python_a_sql
-Falta el ERD
