### ISSUE TITLE
[MartaRG] (w3-project_SQL)

### ISSUE THREAD

**Issue by MartaRggc** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#3]
https://github.com/MartaRggc/Lets_blockbust.git

**Comment by OrianAmpuero** [comment]
Muy bien Marta!
-Excelente readme y organización del repo
-En cuanto a data yo no pondría todos los csv ya que visualmente lía un poco, es mejor poner en el .gitignore los que están sucios y solo dejar a la vista los limpios
-Buena limpieza y análisis comentado de cada tabla
