### ISSUE TITLE
[IbaiGallego] (w3-project_SQL)

### ISSUE THREAD

**Issue by IbaiGallego** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#5]
https://github.com/IbaiGallego/sql-data-base-building.git

**Comment by OrianAmpuero** [comment]
Muy bien Ibai!
-Excelente readme y repo 
-Bien en cuanto a limpieza de csv, yo solo te diría que dejarás los nuevos que están limpios y el resto los pusieras en .gitignore para que no se vean tantos
-No hace falta repetir el mismo archivo de limpieza dos veces (si lo pones en tu carpeta de my_code es suficiente y no entiendo porque tienes el mismo archivo también en .py
