### ISSUE TITLE
[borja.dolagaray][Project_W3_SQL]

### ISSUE THREAD

**Issue by borjadola** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#6]
https://github.com/borjadola/Proyecto_Pandas_SQL.git

**Comment by OrianAmpuero** [comment]
Excelente trabajo Borja! Me dejas poco que comentarte, en cuanto a la organización del repo y el readme muy bien, las queries correctas junto con la limpieza de las tablas y la carga a SQL. Sigue así😊
