### ISSUE TITLE
[David](Project_SQL)

### ISSUE THREAD

**Issue by DavidNPastrana** [Ironhack-Data-Madrid-Julio-2023/w3-project_SQL#9]
https://github.com/DavidNPastrana/SQL_project

**Comment by OrianAmpuero** [comment]
Muy buen trabajo David! Todo correcto tanto la parte del repo y su organización, el readme bien desarrollado y el código de limpieza y queries de SQL. Lo único fue que faltó fue el ERD, es importante ya que te da una vista de las relaciones que hiciste y puedes poner el pantallazo en el readme para darle al proyecto un toque más de base de dato.
